- type: job
  id: BoSMidScribe
  setPreference: false # Delete line for RP
  name: job-name-bos-mid-scribe
  description: job-description-bos-mid-scribe
  playTimeTracker: BoSMidScribe
  startingGear: BoSMidScribeGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-bos-mid
  access:
  - MidwestBoSEntrance
  - MidwestBoSCommon
  - MidwestBoSScribe

- type: startingGear
  id: BoSMidScribeGear
  equipment:
    head: N14ClothingHeadHatBrotherhoodCap
    jumpsuit: N14ClothingUniformJumpsuitBOSBlack
    back: N14ClothingBackpackMilitaryFilled
    shoes: N14ClothingShoesBootsJack
    outerClothing: N14ClothingOuterBrotherhoodFieldScribeCoat
    id: N14IDBrotherhoodHolotag
    ears: N14ClothingHeadsetBOSMidwest
    belt: N14ClothingBeltUtilityFilled
  innerclothingskirt: N14ClothingUniformJumpskirtBOSBlack
  satchel: N14ClothingBackpackSatchelMilitaryFilled
  duffelbag: N14ClothingBackpackDuffelMilitaryFilled
  
- type: playTimeTracker
  id: BoSMidScribe