- type: job
  id: Survivor
  name: job-name-survivor
  playTimeTracker: Survivor
  startingGear: SurvivorGear
  icon: "Passenger"
  supervisors: job-supervisors-wastelander
  setPreference: false

- type: startingGear
  id: SurvivorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitRags
    back: ClothingBackpack
    shoes: ClothingShoesColorBlack
    pocket1: RadioHandheld
    pocket2: N14KitchenKnife
  innerclothingskirt: ClothingUniformJumpskirtMerc
  satchel: ClothingBackpackSatchel
  duffelbag: ClothingBackpackDuffel
