- type: job
  id: BoSMidKnightCommander
  name: job-name-bos-mid-knight-comm
  playTimeTracker: BoSMidKnightCommander
  startingGear: BoSMidKnightCommGear
  icon: "Warden"
  canBeAntag: false
  accessGroups:
  - MidwestBoS
  
- type: startingGear
  id: BoSMidKnightCommGear
  equipment:
    head: #placeholder
    jumpsuit: N14ClothingUniformJumpsuitBOSGold
    back: ClothingBackpackSecurityFilled #placeholder
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesGlassesSunglasses
    outerClothing: N14ClothingOuterCombatArmorBOSCaptain
    id: #placeholder
    ears: ClothingHeadsetSecurity #placeholder
    belt: ClothingBeltSecurityFilled #placeholder
  innerclothingskirt: N14ClothingUniformJumpskirtBOSGold
  satchel: ClothingBackpackSatchelSecurityFilled #placeholder
  duffelbag: ClothingBackpackDuffelSecurityFilled #placeholder
