- type: job
  id: BoSMidScribe
  name: job-name-bos-mid-scribe
  playTimeTracker: BoSMidScribe
  startingGear: BoSMidScribeGear
  icon: "Scientist"
  supervisors: job-supervisors-bos-mid
  access:
  - MidwestBoSEntrance
  - MidwestBoSCommon
  - MidwestBoSScribe

- type: startingGear
  id: BoSMidScribeGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSBlack
    back: ClothingBackpackScienceFilled #placeholder
    shoes: ClothingShoesBootsJack
    outerClothing: N14ClothingOuterCombatArmorBOS
    id: #placeholder
    ears: ClothingHeadsetScience #placeholder
  innerclothingskirt: N14ClothingUniformJumpskirtBOSBlack
  satchel: ClothingBackpackSatchelScienceFilled #placeholder
  duffelbag: ClothingBackpackDuffelScienceFilled #placeholder
