- type: job
  id: BoSWashingtonElder
  setPreference: false # Delete line for RP
  name: job-name-bos-washington-elder
  description: job-description-bos-washington-elder
  playTimeTracker: BoSWashingtonElder
  weight: 10
  startingGear: BoSWashingtonElderGear
  icon: "JobIconHeadOfSecurity"
  supervisors: job-supervisors-bos-washington-elder
  requireAdminNotify: true
  canBeAntag: false
  accessGroups:
  - WashingtonBoS

- type: startingGear
  id: BoSWashingtonElderGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSGold
    back: N14ClothingBackpackMilitaryFilled
    shoes: N14ClothingShoesBootsJack
    outerClothing: N14ClothingOuterBrotherhoodElderCoat
    head: N14ClothingHeadHatBrotherhoodBeret
    id: N14IDBrotherhoodHolotag
    ears: N14ClothingHeadsetBOSWashington
    belt: N14ClothingBeltMilitaryFilled
  innerclothingskirt: N14ClothingUniformJumpskirtBOSGold
  satchel: N14ClothingBackpackSatchelMilitaryFilled
  duffelbag: N14ClothingBackpackDuffelMilitaryFilled

- type: playTimeTracker
  id: BoSWashingtonElder