- type: job
  id: BoSWashingtonElder
  name: job-name-bos-washington-elder
  playTimeTracker: BoSWashingtonElder
  weight: 10
  startingGear: BoSWashingtonElderGear
  icon: "HeadOfSecurity"
  supervisors: job-supervisors-bos-washington-elder
  requireAdminNotify: true
  canBeAntag: false
  accessGroups:
  - WashingtonBoS

- type: startingGear
  id: BoSWashingtonElderGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSGold
    back: ClothingBackpackSecurityFilled #placeholder
    shoes: ClothingShoesBootsJack
    outerClothing: N14ClothingOuterCombatArmorBOSMK2 #placeholder
    id: #placeholder
    ears: ClothingHeadsetAltSecurity #placeholder
    belt: ClothingBeltSecurityFilled #placeholder
  innerclothingskirt: N14ClothingUniformJumpskirtBOSGold
  satchel: ClothingBackpackSatchelSecurityFilled #placeholder
  duffelbag: ClothingBackpackDuffelSecurityFilled #placeholder
