- type: job
  id: BoSWashingtonInitiate
  name: job-name-bos-washington-initiate
  playTimeTracker: BoSWashingtonInitiate
  startingGear: BoSWashingtonInitiateGear
  icon: "SecurityCadet"
  supervisors: job-supervisors-bos-washington-initiate
  canBeAntag: false
  access:
  - WashingtonBoSCommon
  - WashingtonBoSInitiate

- type: startingGear
  id: BoSWashingtonInitiateGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSRed
    back: ClothingBackpackSecurityFilled #placeholder
    shoes: ClothingShoesBootsJack
    id: #placeholder
    ears: ClothingHeadsetSecurity #placeholder
  innerclothingskirt: ClothingUniformJumpskirtColorRed # TODO: Red jumpskirt for BOS?
  satchel: ClothingBackpackSatchelSecurityFilled #placeholder
  duffelbag: ClothingBackpackDuffelSecurityFilled #placeholder
