- type: job
  id: BoSWashingtonKnight
  name: job-name-bos-washington-knight
  playTimeTracker: BoSWashingtonKnight
  startingGear: BoSWashingtonKnightGear
  icon: "Warden"
  supervisors: job-supervisors-bos-washington
  canBeAntag: false
  access:
  - WashingtonBoSCommon
  - WashingtonBoSEntrance
  - WashingtonBoSKnight
  
- type: startingGear
  id: BoSWashingtonKnightGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSBlack
    back: ClothingBackpackSecurityFilled #placeholder
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHelmetHelmetOld
    outerClothing: N14ClothingOuterCombatArmorBOSKnight
    id: #placeholder
    ears: ClothingHeadsetSecurity #placeholder
    belt: ClothingBeltSecurityFilled #placeholder
  innerclothingskirt: N14ClothingUniformJumpskirtBOSBlack
  satchel: ClothingBackpackSatchelSecurityFilled #placeholder
  duffelbag: ClothingBackpackDuffelSecurityFilled #placeholder
