- type: job
  id: BoSWashingtonPaladin
  name: job-name-bos-washington-paladin
  playTimeTracker: BoSWashingtonPaladin
  startingGear: BoSWashingtonPaladinGear
  icon: "SecurityOfficer"
  supervisors: job-name-bos-washington
  canBeAntag: false
  access:
  - WashingtonBoSEntrance
  - WashingtonBoSCommon
  - WashingtonBoSPaladin
  - WashingtonBoSKnight

- type: startingGear
  id: BoSWashingtonPaladinGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSSilver
    back: ClothingBackpackSecurityFilled #placeholder
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHelmetHelmetOld #placeholder
    outerClothing: N14ClothingOuterCombatArmorBOSSenior
    id: #placeholder
    ears: ClothingHeadsetSecurity #placeholder
    belt: ClothingBeltSecurityFilled #placeholder
  innerclothingskirt: N14ClothingUniformJumpskirtBOSSilver
  satchel: ClothingBackpackSatchelSecurityFilled #placeholder
  duffelbag: ClothingBackpackDuffelSecurityFilled #placeholder
