- type: job
  id: BoSWashingtonScribe
  name: job-name-bos-washington-scribe
  playTimeTracker: BoSWashingtonScribe
  startingGear: BoSWashingtonScribeGear
  icon: "Scientist"
  supervisors: job-name-bos-washington
  access:
  - WashingtonBoSCommon
  - WashingtonBoSScribe

- type: startingGear
  id: BoSWashingtonScribeGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSBlack
    back: ClothingBackpackScienceFilled #placeholder
    shoes: ClothingShoesBootsJack
    outerClothing: N14ClothingOuterCombatArmorBOS
    id: #placeholder
    ears: ClothingHeadsetScience #placeholder
  innerclothingskirt: N14ClothingUniformJumpskirtBOSBlack
  satchel: ClothingBackpackSatchelScienceFilled #placeholder
  duffelbag: ClothingBackpackDuffelScienceFilled #placeholder
