- type: job
  id: Overseer
  name: job-name-overseer
  playTimeTracker: Overseer
  weight: 20
  startingGear: OverseerGear
  icon: "Captain"
  requireAdminNotify: true
  joinNotifyCrew: true
  canBeAntag: false
  supervisors: job-supervisors-vault-overseer
  accessGroups:
  - VaultOverseer

- type: startingGear
  id: OverseerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitVault14
    back: N14ClothingBackpackVaultOverseerFilled
    shoes: ClothingShoesColorBlack
    eyes: ClothingEyesGlassesSunglasses
    id: CaptainPDA #placeholder
    ears: ClothingHeadsetAltCommand #placeholder
  innerclothingskirt: ClothingUniformJumpsuitVault14
  satchel: ClothingBackpackSatchelCaptainFilled #placeholder
  duffelbag: ClothingBackpackDuffelCaptainFilled #placeholder
