- type: job
  id: VaultEngineer
  name: job-name-vault-engineer
  playTimeTracker: VaultEngineer
  startingGear: VaultEngineerGear
  icon: "StationEngineer"
  supervisors: job-supervisors-overseer
  access:
  - VaultDweller
  - VaultEngineer

- type: startingGear
  id: VaultEngineerGear
  equipment:
    head: ClothingHeadHatHardhatYellow
    jumpsuit: ClothingUniformJumpsuitVault14
    back: N14ClothingBackpackVaultEngineerFilled
    shoes: ClothingShoesBootsWork
    outerClothing: ClothingOuterVestHazard
    id: EngineerPDA #placeholder
    belt: N14ClothingBeltUtilityFilled
    ears: ClothingHeadsetEngineering #placeholder
  innerclothingskirt: ClothingUniformJumpsuitVault14
  satchel: ClothingBackpackSatchelEngineeringFilled #placeholder
  duffelbag: ClothingBackpackDuffelEngineeringFilled #placeholder
