- type: job
  id: VaultSecurity
  name: job-name-vault-security
  playTimeTracker: VaultSecurity
  startingGear: VaultSecurityGear
  icon: "SecurityOfficer"
  supervisors: job-supervisors-overseer
  canBeAntag: false
  access:
  - VaultDweller
  - VaultSecurity

- type: startingGear
  id: VaultSecurityGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitVault14
    back: ClothingBackpackSecurityFilled #placeholder
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesSunglasses
    head: ClothingHeadHelmetHelmetOld
    outerClothing: N14ClothingOuterVaultSecVest
    id: SecurityPDA #placeholder
    ears: ClothingHeadsetSecurity #placeholder
    belt: ClothingBeltSecurityFilled #placeholder
  innerclothingskirt: N14ClothingUniformJumpsuitVault14 #placeholder
  satchel: ClothingBackpackSatchelSecurityFilled #placeholder
  duffelbag: ClothingBackpackDuffelSecurityFilled #placeholder
