- type: job
  id: VaultDoctor
  name: job-name-vault-doctor
  playTimeTracker: VaultDoctor
  startingGear: VaultDoctorGear
  icon: "MedicalDoctor"
  supervisors: job-supervisors-overseer
  access:
  - VaultDweller
  - VaultMedical

- type: startingGear
  id: VaultDoctorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitVault14
    back: N14ClothingBackpackVaultDoctorFilled
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatLab
    id: MedicalPDA #placeholder
    ears: ClothingHeadsetMedical #placeholder
    belt: ClothingBeltMedicalFilled
  innerclothingskirt: ClothingUniformJumpsuitVault14
  satchel: ClothingBackpackSatchelMedicalFilled #placeholder
  duffelbag: ClothingBackpackDuffelMedicalFilled #placeholder
