- type: job
  id: NCRNCO
  name: job-name-ncr-nco
  playTimeTracker: NCRNCO
  startingGear: NCRNCOGear
  icon: "SecurityOfficer"
  supervisors: job-supervisors-ncr
  canBeAntag: false
  access:
  - NCR3
  
- type: startingGear
  id: NCRNCOGear
  equipment:
    head: ClothingHeadHatBeret
    jumpsuit: N14ClothingUniformJumpsuitCombat
    back: ClothingBackpackSecurityFilled #placeholder
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesSunglasses
    outerClothing: N14ClothingOuterCombatArmor
    id: #placeholder
    ears: ClothingHeadsetSecurity #placeholder
    belt: ClothingBeltSecurityFilled #placeholder
  innerclothingskirt: N14ClothingUniformJumpsuitCombat #placeholder
  satchel: ClothingBackpackSatchelSecurityFilled #placeholder
  duffelbag: ClothingBackpackDuffelSecurityFilled #placeholder
