- type: job
  id: NCRCadet
  name: job-name-ncr-cadet
  playTimeTracker: NCRCadet
  startingGear: NCRCadetGear
  icon: "SecurityCadet"
  supervisors: job-supervisors-ncr-nco
  canBeAntag: false
  access:
  - NCR1

- type: startingGear
  id: NCRCadetGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitCombat
    back: ClothingBackpackSecurityFilled #placeholder
    shoes: ClothingShoesBootsJack
    id: #placeholder
    ears: ClothingHeadsetSecurity #placeholder
  innerclothingskirt: N14ClothingUniformJumpsuitCombat #placeholder
  satchel: ClothingBackpackSatchelSecurityFilled #placeholder
  duffelbag: ClothingBackpackDuffelSecurityFilled #placeholder
