- type: job
  id: NCRSoldier
  name: job-name-ncr-soldier
  playTimeTracker: NCRSoldier
  startingGear: NCRSoldierGear
  icon: "Warden"
  supervisors: job-supervisors-ncr-nco
  canBeAntag: false
  access:
  - NCR2

- type: startingGear
  id: NCRSoldierGear
  equipment:
    head: ClothingHeadHelmetHelmetOld
    jumpsuit: N14ClothingUniformJumpsuitCombat
    back: ClothingBackpackSecurityFilled #placeholder
    shoes: ClothingShoesBootsJack
    outerClothing: N14ClothingOuterLeatherArmor
    id: #placeholder
    ears: ClothingHeadsetSecurity #placeholder
    belt: ClothingBeltSecurityFilled #placeholder
  innerclothingskirt: N14ClothingUniformJumpsuitCombat #placeholder
  satchel: ClothingBackpackSatchelSecurityFilled #placeholder
  duffelbag: ClothingBackpackDuffelSecurityFilled #placeholder
