- type: job
  id: NCROfficer
  name: job-name-ncr-officer
  playTimeTracker: NCROfficer
  weight: 10
  startingGear: NCROfficerGear
  icon: "HeadOfSecurity"
  requireAdminNotify: true
  canBeAntag: false
  accessGroups:
  - NCR

- type: startingGear
  id: NCROfficerGear
  equipment:
    head: ClothingHeadHatBeretHoS
    jumpsuit: N14ClothingUniformJumpsuitCombat
    back: ClothingBackpackSecurityFilled #placeholder
    shoes: ClothingShoesBootsJack
    outerClothing: N14ClothingOuterCombatArmorMK2
    eyes: ClothingEyesSunglasses
    id: #placeholder
    ears: ClothingHeadsetAltSecurity #placeholder
    belt: ClothingBeltSecurityFilled #placeholder
  innerclothingskirt: N14ClothingUniformJumpsuitCombat #placeholder
  satchel: ClothingBackpackSatchelSecurityFilled #placeholder
  duffelbag: ClothingBackpackDuffelSecurityFilled #placeholder
