- type: job
  id: WastelandBartender
  name: job-name-bartender
  playTimeTracker: WastelandBartender
  startingGear: WastelandBartenderGear
  icon: "Bartender"
  supervisors: job-supervisors-wastelander

- type: startingGear
  id: WastelandBartenderGear
  equipment:
    head: ClothingHeadHatTophat
    jumpsuit: N14ClothingUniformJumpsuitBartenderAlt
    outerClothing: N14ClothingOuterLeatherArmor
    back: ClothingBackpackFilled #placeholder
    shoes: ClothingShoesColorBlack
  innerclothingskirt: N14ClothingUniformJumpsuitBartenderAlt #placeholder
  satchel: ClothingBackpackSatchelFilled #placeholder
  duffelbag: ClothingBackpackDuffelFilled #placeholder
