- type: job
  id: WastelandMusician
  name: job-name-musician
  playTimeTracker: WastelandMusician
  startingGear: WastelandMusicianGear
  icon: "Musician"
  supervisors: job-supervisors-hire
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: MikuDay
    prototype: BoxPerformer

- type: startingGear
  id: WastelandMusicianGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitManagerSuit
    back: N14ClothingBackpackMusicianFilled
    eyes: ClothingEyesGlassesSunglasses
    shoes: ClothingShoesColorBlack
  satchel: N14ClothingBackpackSatchelMusicianFilled
  duffelbag: N14ClothingBackpackDuffelMusicianFilled
