- type: job
  id: WastelandScavenger
  name: job-name-scavenger
  playTimeTracker: WastelandScavenger
  startingGear: ScavengerGear
  icon: "Janitor"
  supervisors: job-supervisors-wastelander
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: GarbageDay
    prototype: WeaponRevolverInspector

- type: startingGear
  id: ScavengerGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitMechanic
    back: ClothingBackpackFilled #placeholder
    shoes: ClothingShoesBootsSalvage
    belt: ClothingBeltJanitorFilled #placeholder
  innerclothingskirt: N14ClothingUniformJumpsuitMechanic
  satchel: ClothingBackpackSatchelFilled #placeholder
  duffelbag: ClothingBackpackDuffelFilled #placeholder
