- type: job
  id: Wastelander
  name: job-name-wastelander
  playTimeTracker: Wastelander
  startingGear: WastelanderGear
  icon: "Passenger"
  supervisors: job-supervisors-wastelander

- type: startingGear
  id: WastelanderGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitRags
    back: ClothingBackpackFilled #placeholder
    shoes: ClothingShoesColorBlack
  innerclothingskirt: N14ClothingUniformJumpskirtFalloutBlack
  satchel: ClothingBackpackSatchelFilled  #placeholder
  duffelbag: ClothingBackpackDuffelFilled #placeholder
